apiVersion: v2
appVersion: "v.1.0.0"
description: Helm chart para el despliegue del ingress gateway vinculado a un proyecto o namespace
name: unity-istio-gateway
type: application
#Esta versión debe actualizarse cuando se ejecuten cambios sobre el Chart, para ser detectados por HELM
version: "0.0.4"
