apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.istioNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.insecureHttpPort }}
        name: http
        protocol: HTTP
      hosts:
      {{- range .Values.hosts }}
      - {{ . | quote }}
      {{- end }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: {{ .Values.securePortNumber }}
        name: https
        protocol: HTTPS
      hosts:
      {{- range .Values.hosts }}
      - {{ . | quote  }}
      {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.secretCertificateName }}